#!/usr/bin/env bash
# Architect Library shell environment — source from install scripts and agent terminals.
#
# Usage (repo root):
#   source scripts/architect_env.sh
#
# Writes user-local file: ~/.config/architect-library/env.sh (via install_node.sh)

# shellcheck source=npm_bootstrap_common.sh
_ARCHITECT_ENV_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "$_ARCHITECT_ENV_ROOT/scripts/npm_bootstrap_common.sh"

architect_env_file() {
  printf '%s\n' "${ARCHITECT_ENV_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/architect-library/env.sh}"
}

architect_profile_marker_begin() { echo '# >>> architect-library env >>>'; }
architect_profile_marker_end() { echo '# <<< architect-library env <<<'; }

# Prepend a directory to PATH only if it is not already present (idempotent).
architect_path_prepend_once() {
  local dir="${1%/}"
  [[ -n "$dir" ]] || return 0
  case ":${PATH:-}:" in
    *":${dir}:"*) ;;
    *) export PATH="${dir}:${PATH:-}" ;;
  esac
}

# Prepend an npm package root to NODE_PATH only once (idempotent).
architect_node_path_prepend_once() {
  local dir="${1%/}"
  [[ -d "$dir" ]] || return 0
  case ":${NODE_PATH:-}:" in
    *":${dir}:"*) ;;
    *) export NODE_PATH="${dir}${NODE_PATH:+:$NODE_PATH}" ;;
  esac
}

# npm CLI shim for Cursor-server / bootstrap installs (no system npm on PATH).
architect_ensure_npm_shim() {
  local node_bin="${1:-${NODE_BIN:-}}"
  local npm_prefix bootstrap shim npm_cli
  npm_prefix="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
  bootstrap="$(architect_npm_bootstrap_dir)"
  npm_cli="$bootstrap/bin/npm-cli.js"
  [[ -n "$node_bin" && -x "$node_bin" && -f "$npm_cli" ]] || return 0
  mkdir -p "$npm_prefix/bin"
  shim="$npm_prefix/bin/npm"
  cat >"$shim" <<EOF
#!/usr/bin/env bash
set -euo pipefail
export NPM_CONFIG_PREFIX="\${NPM_CONFIG_PREFIX:-$npm_prefix}"
exec "$node_bin" "$npm_cli" "\$@"
EOF
  chmod +x "$shim"
}

# Apply PATH, NODE_PATH, NPM prefix, and npm shim (safe to call repeatedly).
architect_apply_env() {
  local env_file npm_prefix
  npm_prefix="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
  export NPM_CONFIG_PREFIX="$npm_prefix"
  env_file="$(architect_env_file)"
  if [[ -f "$env_file" ]]; then
    # shellcheck source=/dev/null
    source "$env_file"
  else
    architect_path_prepend_once "$npm_prefix/bin"
    architect_node_path_prepend_once "$npm_prefix/lib/node_modules"
  fi
  if [[ -n "${NODE_BIN:-}" && -x "${NODE_BIN}" ]]; then
    architect_path_prepend_once "$(dirname "$NODE_BIN")"
    architect_ensure_npm_shim "$NODE_BIN"
  fi
}

# Persist env for login shells (idempotent PATH/NODE_PATH case blocks).
architect_write_env_file() {
  local node_bin="${1:-}"
  local env_file dir npm_prefix bootstrap
  env_file="$(architect_env_file)"
  dir="$(dirname "$env_file")"
  mkdir -p "$dir"
  npm_prefix="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
  bootstrap="$(architect_npm_bootstrap_dir)"
  if [[ -n "$node_bin" && -x "$node_bin" ]]; then
    architect_ensure_npm_shim "$node_bin"
  fi
  {
    echo '# Generated by architect-library scripts/install_node.sh — safe to re-run.'
    echo "export NPM_CONFIG_PREFIX=\"$npm_prefix\""
    echo "export ARCHITECT_NPM_BOOTSTRAP=\"$bootstrap\""
    if [[ -n "$node_bin" && -x "$node_bin" ]]; then
      echo "export NODE_BIN=\"$node_bin\""
    fi
    echo "case \":\${PATH:-}:\" in *\":$npm_prefix/bin:\"*) ;; *) export PATH=\"$npm_prefix/bin:\${PATH:-}\" ;; esac"
    if [[ -n "$node_bin" && -x "$node_bin" ]]; then
      echo "case \":\${PATH:-}:\" in *\":$(dirname "$node_bin"):\"*) ;; *) export PATH=\"$(dirname "$node_bin"):\${PATH:-}\" ;; esac"
    fi
    echo "case \":\${NODE_PATH:-}:\" in *\":$npm_prefix/lib/node_modules:\"*) ;; *) export NODE_PATH=\"$npm_prefix/lib/node_modules\${NODE_PATH:+:\$NODE_PATH}\" ;; esac"
  } >"$env_file"
  echo "✓ Wrote $env_file"
}

# Append a guarded source line to ~/.bashrc (and ~/.profile if no bashrc hook yet).
architect_ensure_shell_profile() {
  local env_file hook rc
  env_file="$(architect_env_file)"
  hook="[[ -f \"$env_file\" ]] && . \"$env_file\""
  for rc in "$HOME/.bashrc" "$HOME/.profile"; do
    [[ -f "$rc" ]] || continue
    if grep -Fq 'architect-library env' "$rc" 2>/dev/null; then
      continue
    fi
    {
      echo ""
      architect_profile_marker_begin
      echo "$hook"
      architect_profile_marker_end
    } >>"$rc"
    echo "✓ Added architect-library env hook to $rc"
  done
  if [[ ! -f "$HOME/.bashrc" && ! -f "$HOME/.profile" ]]; then
    {
      architect_profile_marker_begin
      echo "$hook"
      architect_profile_marker_end
    } >>"$HOME/.bashrc"
    echo "✓ Created ~/.bashrc with architect-library env hook"
  fi
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  architect_apply_env
elif [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  architect_apply_env
  echo "Architect Library env applied (NPM_CONFIG_PREFIX=${NPM_CONFIG_PREFIX:-})"
  if command -v npm &>/dev/null; then
    echo "  npm: $(command -v npm)"
  fi
  if command -v node &>/dev/null; then
    echo "  node: $(command -v node)"
  elif [[ -n "${NODE_BIN:-}" && -x "${NODE_BIN}" ]]; then
    echo "  node: $NODE_BIN"
  fi
  [[ -n "${NODE_PATH:-}" ]] && echo "  NODE_PATH: $NODE_PATH"
fi
