#!/usr/bin/env bash
# Architect Library shell environment — source from install scripts and agent terminals.
#
# Usage (repo root):
#   source scripts/architect_env.sh
#
# Writes user-local file: ~/.config/architect-library/env.sh (via install_node.sh)

architect_env_file() {
  printf '%s\n' "${ARCHITECT_ENV_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/architect-library/env.sh}"
}

architect_profile_marker_begin() { echo '# >>> architect-library env >>>'; }
architect_profile_marker_end() { echo '# <<< architect-library env <<<'; }

# Apply PATH, NODE_PATH, and NPM prefix for child processes (idempotent).
architect_apply_env() {
  local env_file
  env_file="$(architect_env_file)"
  export NPM_CONFIG_PREFIX="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
  if [[ -f "$env_file" ]]; then
    # shellcheck source=/dev/null
    source "$env_file"
  fi
  export NPM_CONFIG_PREFIX="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
  export PATH="$NPM_CONFIG_PREFIX/bin:${PATH:-}"
  if [[ -d "$NPM_CONFIG_PREFIX/lib/node_modules" ]]; then
    case ":${NODE_PATH:-}:" in
      *":$NPM_CONFIG_PREFIX/lib/node_modules:"*) ;;
      *) export NODE_PATH="${NPM_CONFIG_PREFIX}/lib/node_modules${NODE_PATH:+:$NODE_PATH}" ;;
    esac
  fi
}

# Persist env for login shells and later sessions (called from install_node.sh).
architect_write_env_file() {
  local node_bin="${1:-}"
  local env_file dir
  env_file="$(architect_env_file)"
  dir="$(dirname "$env_file")"
  mkdir -p "$dir"
  NPM_PREFIX="${NPM_CONFIG_PREFIX:-$HOME/.npm-global}"
  {
    echo '# Generated by architect-library scripts/install_node.sh — safe to re-run.'
    echo "export NPM_CONFIG_PREFIX=\"$NPM_PREFIX\""
    echo "export PATH=\"$NPM_PREFIX/bin:\${PATH:-}\""
    echo "export NODE_PATH=\"$NPM_PREFIX/lib/node_modules\${NODE_PATH:+:\$NODE_PATH}\""
    if [[ -n "$node_bin" && -x "$node_bin" ]]; then
      echo "export NODE_BIN=\"$node_bin\""
      echo "export PATH=\"$(dirname "$node_bin"):\${PATH:-}\""
    fi
  } >"$env_file"
  echo "✓ Wrote $env_file"
}

# Append a guarded source line to ~/.bashrc (and ~/.profile if no bashrc hook yet).
architect_ensure_shell_profile() {
  local env_file hook rc profile line
  env_file="$(architect_env_file)"
  hook="[[ -f \"$env_file\" ]] && . \"$env_file\""
  line="$(architect_profile_marker_begin)"
  for rc in "$HOME/.bashrc" "$HOME/.profile"; do
    [[ -f "$rc" ]] || continue
    if grep -Fq 'architect-library env' "$rc" 2>/dev/null; then
      continue
    fi
    {
      echo ""
      architect_profile_marker_begin
      echo "$hook"
      architect_profile_marker_end
    } >>"$rc"
    echo "✓ Added architect-library env hook to $rc"
  done
  if [[ ! -f "$HOME/.bashrc" && ! -f "$HOME/.profile" ]]; then
    {
      architect_profile_marker_begin
      echo "$hook"
      architect_profile_marker_end
    } >>"$HOME/.bashrc"
    echo "✓ Created ~/.bashrc with architect-library env hook"
  fi
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  architect_apply_env
elif [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  architect_apply_env
  echo "Architect Library env applied (NPM_CONFIG_PREFIX=${NPM_CONFIG_PREFIX:-})"
  if command -v node &>/dev/null; then
    echo "  node: $(command -v node)"
  elif [[ -n "${NODE_BIN:-}" && -x "${NODE_BIN}" ]]; then
    echo "  node: $NODE_BIN"
  fi
  [[ -n "${NODE_PATH:-}" ]] && echo "  NODE_PATH: $NODE_PATH"
fi
